name: Fast DDS Docs Ubuntu CI (weekly)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # Run at minute 0 on Monday

jobs:
  weekly-ubuntu-ci-2_6_x:
    uses: eProsima/Fast-DDS-docs/.github/workflows/reusable-ubuntu-ci.yml@2.6.x
    with:
      # It would be desirable to have a matrix of ubuntu OS for this job, but due to the issue opened in this ticket:
      # https://github.com/orgs/community/discussions/128118 , it has been set as a single OS job.
      os-version: 'ubuntu-20.04'
      label: '-weekly-ubuntu-ci-2.6.x'
      fastdds-docs-branch: '2.6.x'
      fastdds-branch: '2.6.x'
      fastdds-python-branch: '1.0.x'
      run-build: true
      run-tests: true
      use-ccache: false
